service: serverless-basic-lambda
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs12.x

  stage: dev
  region: ap-south-1

functions:
  hello:
    handler: src/handler.uploadToS3
    timeout: 60 #seconds
    memorySize: 128 #mb
